DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    phone VARCHAR(30),
    address VARCHAR(200),
    city VARCHAR(100),
    postal_code VARCHAR(20)
);
